name: CI Tests and Coverage

on:
  push:
    branches: [main, develop, feature_*]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv package manager
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Install project dependencies
        run: |
          uv sync --dev

      - name: Run tests with coverage
        run: |
          uv run pytest \
            --cov=lumi_filter \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-fail-under=70

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: lumi-filter-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload coverage HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov/
          retention-days: 30

      - name: Upload coverage XML for processing
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 7
